apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meu-site-pro
  namespace: argocd
  labels:
    app.kubernetes.io/name: meu-site
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: kubectl
    environment: production
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  project: application
  source:
    repoURL: git@github.com:HenriqZimer/meu-site-helm-chart.git
    path: chart
    targetRevision: main
    helm:
      releaseName: meu-site
      valueFiles:
        - values-pro.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: meu-site