apiVersion: v1
kind: Secret
metadata:
  name: harbor-docker-credentials
  namespace: imagepullsecret-patcher
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: >-
    {"auths":{"harbor.henriqzimer.com.br":{"auth":"YWRtaW46alIwJU9RaDhaSjdCdXc="}}}
